### ISSUE TITLE
HTTP/HTTPS push update function call panic

### ISSUE THREAD

**Issue by facat** [gogits/gogs#1037]
I push my local repo to the remote repo, git said success but no update was made  on the remote repo.

This is what git said:

    remote: Incorrect Usage.[K
    remote: 
    remote: NAME:[K
    remote:    update - This command should only be called by SSH shell[K
    remote: 
    remote: USAGE:[K
    remote:    command update [arguments...][K
    remote: 
    remote: DESCRIPTION:[K
    remote:    Update get pushed info and insert into database[K
    remote: 
    Pushing to http://emp2:3000/facat/pes2014-wronglowervoltagebound.git
    To http://emp2:3000/facat/pes2014-wronglowervoltagebound.git
       584ff70..5ab0432  master -> master
    updating local tracking ref 'refs/remotes/cubie/master'

and I found error log in gogs console:

    [Macaron] Started POST /facat/pes2014-wronglowervoltagebound.git/git-receive-pack for 1.185.17
    .115
    [Macaron] PANIC: runtime error: invalid memory address or nil pointer dereferenc
    e
    /home/cubie/down/go/src/runtime/panic.go:387 (0x24ba8)
            gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz),
    uint32(d.siz))
    /home/cubie/down/go/src/runtime/panic.go:42 (0x23e68)
            panicmem: panic(memoryError)
    /home/cubie/down/go/src/runtime/sigpanic_unix.go:26 (0x2ad20)
            sigpanic: panicmem()
    /home/cubie/App/goApp/src/github.com/gogits/gogs/routers/repo/http.go:192 (0x2a5
    c80)
            func.003: models.Update(refName, oldCommitId, newCommitId, authUsername,
     username, reponame, authUser.Id)
    /home/cubie/App/goApp/src/github.com/gogits/gogs/routers/repo/http.go:334 (0x285
    784)
            serviceRpc: return
    /home/cubie/App/goApp/src/github.com/gogits/gogs/routers/repo/http.go:282 (0x284
    de0)
            serviceReceivePack: serviceRpc("receive-pack", hr)
    /home/cubie/App/goApp/src/github.com/gogits/gogs/routers/repo/http.go:266 (0x2a6
    0d0)
            func.004: route.handler(hr)
    /home/cubie/App/goApp/src/github.com/gogits/gogs/routers/repo/http.go:123 (0x284
    6b0)
            Http: return
    /home/cubie/down/go/src/runtime/asm_arm.s:406 (0x4d490)
            call16: MOVBU.P 1(R1), R5;                      \
    /home/cubie/down/go/src/reflect/value.go:373 (0x2ca8c4)
            Value.call: for i := 0; i < m; i++ {
    /home/cubie/down/go/src/reflect/value.go:296 (0x2c9950)
            Value.Call: return v.call("Call", in)
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/inject/inject.go:102 (0x4da
    8e8)
            (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/context.go:112 (0x1de350)
            (*Context).run: vals, err := c.Invoke(c.handler())
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/context.go:103 (0x1de268)
            (*Context).Next: c.run()
    /home/cubie/App/goApp/src/github.com/macaron-contrib/session/session.go:188 (0x2
    1b694)
            func.004: ctx.Next()
    /home/cubie/down/go/src/runtime/asm_arm.s:406 (0x4d490)
            call16: MOVBU.P 1(R1), R5;                      \
    /home/cubie/down/go/src/reflect/value.go:373 (0x2ca8c4)
            Value.call: for i := 0; i < m; i++ {
    /home/cubie/down/go/src/reflect/value.go:296 (0x2c9950)
            Value.Call: return v.call("Call", in)
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/inject/inject.go:102 (0x4da
    8e8)
            (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/context.go:112 (0x1de350)
            (*Context).run: vals, err := c.Invoke(c.handler())
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/context.go:103 (0x1de268)
            (*Context).Next: c.run()
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/recovery.go:161 (0x1f01e8)
            func.008: c.Next()
    /home/cubie/down/go/src/runtime/asm_arm.s:406 (0x4d490)
            call16: MOVBU.P 1(R1), R5;                      \
    /home/cubie/down/go/src/reflect/value.go:373 (0x2ca8c4)
            Value.call: for i := 0; i < m; i++ {
    /home/cubie/down/go/src/reflect/value.go:296 (0x2c9950)
            Value.Call: return v.call("Call", in)
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/inject/inject.go:102 (0x4da
    8e8)
            (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/context.go:112 (0x1de350)
            (*Context).run: vals, err := c.Invoke(c.handler())
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/context.go:103 (0x1de268)
            (*Context).Next: c.run()
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/logger.go:40 (0x1ef1d0)
            func.004: ctx.Next()
    /home/cubie/down/go/src/runtime/asm_arm.s:406 (0x4d490)
            call16: MOVBU.P 1(R1), R5;                      \
    /home/cubie/down/go/src/reflect/value.go:373 (0x2ca8c4)
            Value.call: for i := 0; i < m; i++ {
    /home/cubie/down/go/src/reflect/value.go:296 (0x2c9950)
            Value.Call: return v.call("Call", in)
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/inject/inject.go:102 (0x4da
    8e8)
            (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/context.go:112 (0x1de350)
            (*Context).run: vals, err := c.Invoke(c.handler())
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/router.go:158 (0x1f1514)
            func.015: c.run()
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/router.go:245 (0x1e8b30)
            (*Router).ServeHTTP: h(rw, req, p)
    /home/cubie/App/goApp/src/github.com/Unknwon/macaron/macaron.go:171 (0x1e2678)
            (*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
    /home/cubie/down/go/src/net/http/server.go:1703 (0x1c0cf4)
            serverHandler.ServeHTTP: handler.ServeHTTP(rw, req)
    /home/cubie/down/go/src/net/http/server.go:1217 (0x1beadc)
            (*conn).serve: }
    /home/cubie/down/go/src/runtime/asm_arm.s:1322 (0x4f6f8)
            goexit: RET
    2015/03/11 21:44:11 http: multiple response.WriteHeader calls
    [Macaron] Completed /facat/pes2014-wronglowervoltagebound.git/git-receive-pack 5
    00 Internal Server Error in 1.750823875s

**Comment by facat** [comment]
Version of Go and Git:

    go version go1.4.2 linux/arm
    git version 2.1.0.GIT

**Comment by Unknwon** [comment]
Hi, I just tested with https://try.gogs.io . So the SSH push/pull is actually working. I would think there maybe some misconfiguration.

Can you go to admin dashboard and click on regenerate ssh key file(`Rewrite '.ssh/autorized_key' file (caution: non-Gogs keys will be lost)`) then test again?

**Comment by facat** [comment]
@Unknwon I tried your method, doesn't work.
I use username/password authentication. Maybe it's unrelated to SSH key.

**Comment by Unknwon** [comment]
Well... let's try `Rewrite all update hook of repositories (needed when custom config path is changed)` again!

**Comment by facat** [comment]
@Unknwon seems fixed.
In fact, when git said success, my local repo is pushed to remote repo. This can be verified because I was able to clone the repo I pushed. However no update information is displayed on gogs web, and the repo is empty when I visit from gogs web.

**Comment by Unknwon** [comment]
@facat I know, from the error message you provide, it's done with `push` process, the update process failed.

**Comment by facat** [comment]
@Unknwon Can you give me some suggestions to fix the update failure?

**Comment by Unknwon** [comment]
> Can you give me some suggestions to fix the update failure?

I thought you said `seems fixed.`?

**Comment by facat** [comment]
@Unknwon 
Sorry. I meant no these messages displayed ever

    remote: Incorrect Usage.[K
    remote: 
    remote: NAME:[K
    remote:    update - This command should only be called by SSH shell[K

But no update is displayed on gogs web.

**Comment by Unknwon** [comment]
Hmm..that odd. Things should work if the error message no longer appear.

**Comment by facat** [comment]
@Unknwon 
I still got these error

    [Macaron] Started POST /facat/pes2014-wronglowervoltagebound.git/git-receive-pack for 1.185.17
    .115
    [Macaron] PANIC: runtime error: invalid memory address or nil pointer dereferenc
    e
    /home/cubie/down/go/src/runtime/panic.go:387 (0x24ba8)
            gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz),
    uint32(d.siz))
    /home/cubie/down/go/src/runtime/panic.go:42 (0x23e68)
            panicmem: panic(memoryError)
    /home/cubie/down/go/src/runtime/sigpanic_unix.go:26 (0x2ad20)
            sigpanic: panicmem()
    /home/cubie/App/goApp/src/github.com/gogits/gogs/routers/repo/http.go:192 (0x2a5
    c80)
    ......

**Comment by Unknwon** [comment]
OK, now make sense. 

Is your repository private? If it's open sourced then will be much easier for us to debug.

**Comment by facat** [comment]
@Unknwon It's private. Do I need to give you the repo?

**Comment by Unknwon** [comment]
Hmm..Would you like to create private repo on https://try.gogs.io then try the same steps?

**Comment by facat** [comment]
@Unknwon 
I create a private repo try.gogs.io/facat/test, and pushed. Still the repo is empty on gogs.

**Comment by Unknwon** [comment]
I see it. Can to pack the repository along with the git history and send to u@gogs.io ?

**Comment by facat** [comment]
@Unknwon 
sent it to you.

**Comment by Unknwon** [comment]
Got it!

**Comment by Unknwon** [comment]
I've reproduced and fixed locally, but found another unrelated bug, will push soon!

**Comment by Unknwon** [comment]
OK, I've pushed fix on `master` branch, please help test again!

**Comment by facat** [comment]
@Unknwon 
It's not fixed. repo on try.gogs.io/facat/test is empty.

**Comment by Unknwon** [comment]
> It's not fixed. repo on try.gogs.io/facat/test and local are empty. And I can still see the same panic error on the local.

I didn't pushed to try.gogs.io, but now did.

Make sure you see `0.5.16.0312` at the bottom of page.

**Comment by facat** [comment]
@Unknwon 
I'm sure 

    © 2015 Gogs · 当前版本: 0.5.16.0312 Beta · 页面: 242ms · 模板: 64ms

**Comment by Unknwon** [comment]
Please test on pushing new code.

**Comment by facat** [comment]
@Unknwon 
Even I created a new repo, I can sill see the panic error.

**Comment by Unknwon** [comment]
Please give reproduce steps to help me debug.

**Comment by facat** [comment]
@Unknwon 
1. Create a private repo on gogs web. Don't initiate it.
2. Create a local repo and git init it.
3. Commit new code on local repo.
4. Add remote repo to the local repo.
5. Push local repo to the remote repo.

**Comment by Unknwon** [comment]
Sorry I still cannot reproduce it. :mask:

**Comment by linphy** [comment]
i reproduce  it ，i get some error

**Comment by linphy** [comment]
my version is 0.5.16.0301 Beta

**Comment by facat** [comment]
@linphy Try the lasted master branch.
@Unknwon I cleaned my GOPATH dir and go git -u github.com/gogits/gogs from scratch. Things work fine this time. Thanks.

**Comment by linphy** [comment]
@Unknwon get 0.5.16.0312 Beta version，then work。Thanks.

**Comment by Unknwon** [comment]
@facat @linphy very well! Thank you both!
