### ISSUE TITLE
Rename repo case change throws error "Repository name has been already taken"

### ISSUE THREAD

**Issue by donnex** [gogits/gogs#1377]
When trying to rename a repo and change the case of the Repository Name from "My-repo" to "my-repo" for example Gogs throws an error that "Repository name has been already taken". The only workaround is to rename it to something else and then change back with the repo name in lower case.

**Comment by Unknwon** [comment]
Hi there, this issue should be fixed in `develop` branch, and you can also test on https://try.gogs.io

**Comment by donnex** [comment]
I just tried this on try.gogs.io but the issue still seems to remain. I created a new repository with renametest as name. I then tried to rename this repo from renametest to RenameTest and got an error that the repository name is already taken.

Screenshot: http://donnex.net/gyazo/47338378cae097a7d15d400e277f0c98.png

**Comment by Unknwon** [comment]
Oops.. my bad, forgot to update Gogs on my machine after post comments. :scream:

Please try again now...

![image](https://cloud.githubusercontent.com/assets/2946214/9600946/48df4706-506c-11e5-9164-7e434856fb50.png)

**Comment by donnex** [comment]
Sweet, now it's working fine :) I was able to rename the repo correctly.

Just a very minor thing but it would be nice if the rename is added to the dashboard log.

**Comment by Unknwon** [comment]
By `dashboard log`, do you mean dashboard news feeds?

**Comment by donnex** [comment]
Yeah, I think so :)

The area where it currently says:
"donnex created repository donnex/renametest"

It would be really nice if the rename of the repo is reflected there. But maybe it's better to open another issue?

**Comment by Unknwon** [comment]
> It would be really nice if the rename of the repo is reflected there. But maybe it's better to open another issue?

Yes, I believe so.

Hmm... I think it's a good thing to add, but since Gogs does not care cases of your repo name, only character changes of repo name will be in the news feeds, does that sounds OK to you?

**Comment by donnex** [comment]
Yeah, if it's only possible to add add an entry to the news feed when a character change is made it's better than nothing. I think it's it's a good addition to Gogs to log these kind of actions.

I was a but confused myself when I renamed a bunch of repositories (imported a bunch of old ones) and nothing was added to the news feed about it.

**Comment by Unknwon** [comment]
> I was a bit confused myself when I renamed a bunch of imported repositories and nothing was added to the news feed about it.

Well... sorry about it... let me see how much work should be done to add a rename action, so we can fix both issues at once.

**Comment by donnex** [comment]
No worries at all, I'm very very happy with Gogs and you're doing an awesome job with it :) This is just a very minor addition to make a really good system even better!

**Comment by Unknwon** [comment]
OK, you can now test on https://try.gogs.io

**Comment by donnex** [comment]
Seems to be working great :)

**Comment by Unknwon** [comment]
Awesome, thanks your confirmation!
