### ISSUE TITLE
LDAP Admin Search failed unexpectedly

### ISSUE THREAD

**Issue by zijam** [gogits/gogs#1554]
When using LDAP authentication gogs logs following error message
```
[...gogs/models/login.go:260 LoginUserLdapSource()] [E] LDAP Admin Search failed unexpectedly! (LDAP Result Code 201 "": ldap: filter does not start with an '(')
```

*Admin Filter* is not mandatory in LDAP setting, but user is still allowed to login.

**Comment by Unknwon** [comment]
Thanks your feedback!

Is it the case that your admin filter is a empty string?

**Comment by zijam** [comment]
Yes .

**Comment by Unknwon** [comment]
Thanks for following up!

I've pushed fixes on `master` which checks if you provide admin filter or not.

**Comment by zijam** [comment]
didn't fix the problem.
Isn't related to file gogs/models/login.go:260

**Comment by Unknwon** [comment]
The error is `ldap: filter does not start with an '('`, which means is the problem with the filter value, from my understanding.

**Comment by Unknwon** [comment]
Make sure you **actually** updated and recompiled and Gogs.

**Comment by zijam** [comment]
It works now :smile:

**Comment by Unknwon** [comment]
@zijam thanks your confirmation!
