### ISSUE TITLE
PAM Login with develop version results in PANIC: runtime error

### ISSUE THREAD

**Issue by hhenkel** [gogits/gogs#1635]
Configuring a PAM authentication in gogs build from the current develop branch gives me the following:

```
2015/09/14 12:06:26 [T] Custom path: /home/gogs/custom
2015/09/14 12:06:26 [T] Log path: /home/gogs/log
2015/09/14 12:06:26 [I] Gogs: Go Git Service 0.6.12.0913 Beta
2015/09/14 12:06:26 [I] Log Mode: File(Info)
2015/09/14 12:06:26 [I] Redis Supported
2015/09/14 12:06:26 [I] Memcache Supported
2015/09/14 12:06:26 [I] Cache Service Enabled
2015/09/14 12:06:26 [I] Session Service Enabled
2015/09/14 12:06:26 [T] Doing: CheckRepoStats
2015/09/14 12:06:26 [I] SQLite3 Supported
2015/09/14 12:06:26 [I] Run Mode: Production
2015/09/14 12:06:26 [I] Listen: http://0.0.0.0:3000/gogs
[Macaron] Started POST /user/login for 10.10.7.49
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:423 (0x4bedc9)
/usr/local/go/src/runtime/panic.go:42 (0x4bd489)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x4d3e3a)
/home/nfs/example.com/myADuser/go/src/github.com/gogits/gogs/models/login.go:391 (0x5dc87e)
        LoginUserPAMSource: return nil, ErrUserNotExist{u.Id, u.Name}
/home/nfs/example.com/myADuser/go/src/github.com/gogits/gogs/models/login.go:426 (0x5dcdd0)
        ExternalUserLogin: return LoginUserPAMSource(u, name, passwd, source.ID, source.Cfg.(*PAMConfig), autoRegister)
/home/nfs/example.com/myADuser/go/src/github.com/gogits/gogs/models/login.go:474 (0x5dd4f3)
        UserSignIn: u, err := ExternalUserLogin(nil, uname, passwd, &source, true)
/home/nfs/example.com/myADuser/go/src/github.com/gogits/gogs/routers/user/auth.go:79 (0x8b9213)
        SignInPost: u, err := models.UserSignIn(form.UserName, form.Password)
/usr/local/go/src/runtime/asm_amd64.s:438 (0x4efe5e)
/usr/local/go/src/reflect/value.go:432 (0x8e5e0a)
/usr/local/go/src/reflect/value.go:300 (0x8e4ad1)
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/inject/inject.go:102 (0xb32192)
        (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/context.go:113 (0x6e4757)
        (*Context).run: vals, err := c.Invoke(c.handler())
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/context.go:104 (0x6e463c)
        (*Context).Next: c.run()
/home/nfs/example.com/myADuser/go/src/github.com/macaron-contrib/session/session.go:188 (0x7c4854)
        Sessioner.func1: ctx.Next()
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4efdbe)
/usr/local/go/src/reflect/value.go:432 (0x8e5e0a)
/usr/local/go/src/reflect/value.go:300 (0x8e4ad1)
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/inject/inject.go:102 (0xb32192)
        (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/context.go:113 (0x6e4757)
        (*Context).run: vals, err := c.Invoke(c.handler())
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/context.go:104 (0x6e463c)
        (*Context).Next: c.run()
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/recovery.go:161 (0x6fa3e2)
        Recovery.func1: c.Next()
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4efdbe)
/usr/local/go/src/reflect/value.go:432 (0x8e5e0a)
/usr/local/go/src/reflect/value.go:300 (0x8e4ad1)
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/inject/inject.go:102 (0xb32192)
        (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/context.go:113 (0x6e4757)
        (*Context).run: vals, err := c.Invoke(c.handler())
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/context.go:104 (0x6e463c)
        (*Context).Next: c.run()
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/logger.go:40 (0x6f902e)
        Logger.func1: ctx.Next()
/usr/local/go/src/runtime/asm_amd64.s:437 (0x4efdbe)
/usr/local/go/src/reflect/value.go:432 (0x8e5e0a)
/usr/local/go/src/reflect/value.go:300 (0x8e4ad1)
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/inject/inject.go:102 (0xb32192)
        (*injector).Invoke: return reflect.ValueOf(f).Call(in), nil
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/context.go:113 (0x6e4757)
        (*Context).run: vals, err := c.Invoke(c.handler())
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/router.go:184 (0x6fbb54)
        (*Router).Handle.func1: c.run()
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/router.go:286 (0x6f1f6d)
        (*Router).ServeHTTP: h(rw, req, p)
/home/nfs/example.com/myADuser/go/src/github.com/Unknwon/macaron/macaron.go:170 (0x6e9c25)
        (*Macaron).ServeHTTP: m.Router.ServeHTTP(rw, req)
/usr/local/go/src/net/http/server.go:1862 (0x6c0f6e)
/usr/local/go/src/net/http/server.go:1361 (0x6be75e)
/usr/local/go/src/runtime/asm_amd64.s:1696 (0x4f20e1)
[Macaron] Completed /user/login 500 Internal Server Error in 56.777419ms

```

I'm currently unsure what the error is causing - we propably got a bit of a special setup as we're using sssd to authenticate AD users through an IPA Server / AD Trust. Login names are somekey@example.com - not sure if this is causing the issue or if I need to modify something in the pam config on the system.

**Comment by Unknwon** [comment]
Hi @hhenkel !

Thanks your feedback!

It is a bug that used a nil object when return error as auth failed.

I've pushed fix to `master`, please help test again!

**Comment by hhenkel** [comment]
Thanks for the update, seems like the null pointer is gone. 

However I still can't login:
```
2015/09/14 18:16:07 [W] Failed to login 'myADuser@example.com' via 'PAM_GOGS': user does not exist: [uid: 0, name: myADuser@example.com]
```

My assumption for an authentictation error is, that I would see an entry in /var/log/secure - but there is nothing. Also /var/log/messages nor journalctl show me anything. SELinux is in permissive mode.

**Comment by Unknwon** [comment]
Close as fixed in another issue(if I remember correctly).

**Comment by hhenkel** [comment]
@Unknwon not sure if it should be closed. 

It is currently fixed for me as I'm using ldap bind dn instead of pam, but that does not mean that the problem with pam is solved. Maybe someone could enlighten me, what I'm doing wrong or what is defective.

**Comment by Unknwon** [comment]
@hhenkel can you do something PAM testing so we can fix this problem?

**Comment by hhenkel** [comment]
@Unknwon sure, I guess I need to enable more logging? Are you aware of someone who is using pam to authenticate so we could take them in the loop?

**Comment by Unknwon** [comment]
Actually, there is not much log Gogs can give you because all Gogs does is send a request to a 3-party lib and get the result....

**Comment by computergeek125** [comment]
I just got PAM working against an Ubuntu shadow file.  There's no fancy AD/LDAP on my system, so I cannot vouch for the PAM interaction with that.

I'm running Gogs 0.9.71.0809 on Ubuntu 14.04.

My issue was with system configuration, not with gogs itself.  I had to allow the gogs user read access to my shadow file (\*facepalm\* like it says in the documentation).  I had hit a wall until I figured that out, and now that it's working, gogs doesn't show up in my auth.log anymore (except for bad passwords).  Previously I had gotten entries like:

```
2016/08/23 22:27:05 [W] Failed to login 'me' via 'pam_gogs': user does not exist [uid: 0, name: me]
```
and
```
Aug 23 22:27:03 odin unix_chkpwd[28855]: check pass; user unknown
Aug 23 22:27:03 odin unix_chkpwd[28855]: password check failed for user (me)
```

Resolution: definitely closed
