### ISSUE TITLE
Wiki preview does not work on Firefox

### ISSUE THREAD

**Issue by windsource** [gogits/gogs#2171]
When creating a wiki page and using the 'Toggle Preview' button sometimes only 'Loading...' appears.

Gogs version 0.8.0.1212 

The bug is reproducable with my own installation and also with https://try.gogs.io/windsource/testrepo/wiki/Home/.

In very rare cases the preview works but most of the time only 'Loading...' appears.

Steps to reproduce:

1. Create a new repository and initialize it with README.md
2. Create a wiki
3. When the very first page is created with the default text press the 'Toggle Preview' button.

**Comment by windsource** [comment]
The problem seems to be related to using the Firefox browser (v 42.0). I was not able to reproduce the problem using the Chrome browser.

**Comment by Unknwon** [comment]
Hi, I've pushed fix to `develop`, you can test again on https://try.gogs.io/windsource/testrepo/wiki/Home/ as well.

**Comment by windsource** [comment]
The problems remains on https://try.gogs.io/windsource/testrepo/wiki/Home/ using Firefox.


![ohne titel](https://cloud.githubusercontent.com/assets/13716595/11774578/d6a98ddc-a236-11e5-9c35-a5bb6d934fa7.png)

**Comment by Unknwon** [comment]
@windsource you may need force refresh.

**Comment by windsource** [comment]
Now it works. Thank you.

**Comment by Unknwon** [comment]
Cool!
