### ISSUE TITLE
SQL Error after upgrade to 0.9.40

### ISSUE THREAD

**Issue by MojoDwarf** [gogits/gogs#3251]
Gogs version built from source: 0.9.40.0709
Database: MariaDB 10.1.14
OS:  FreeBSD 10.3-RELEASE-p5
GO version: 1.6.2_1,1

 **_[...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ADD `enable_prune` TINYINT(1) NOT NULL DEFAULT true' at line 1_**

The build is successful but attempting to start "./gogs web" gives the above error, looks like potentially a problem updating the existing database schema?

**Comment by Unknwon** [comment]
Maybe because `MariaDB` is not exactly same as `MySQL`? Demo server uses MySQL and upgrades smoothly...

**Comment by Unknwon** [comment]
cc/ @lunny

**Comment by zcalusic** [comment]
I'm using PostgreSQL and got the same error an hour before, trying to upgrade from 0.9.34.0630 to 0.9.40.0709

...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: sync database struct error: pq: syntax error at or near ""enable_prune""

**Comment by Unknwon** [comment]
@zcalusic can you checkout `github.com/go-xorm/xorm` to revision `8150bebe6a68d3e86a14e3aa0cbac4873c05131d`, then recompile Gogs and restart?

**Comment by zcalusic** [comment]
Would love to, but xorm is uncompilable @ that commit:

# github.com/go-xorm/xorm
./engine.go:384: cannot use true (type bool) as type int in assignment
./engine.go:879: cannot use true (type bool) as type int in assignment
./engine.go:884: cannot use true (type bool) as type int in assignment
./engine.go:939: cannot use make(map[string]bool) (type map[string]bool) as type map[string]int in field value
./mssql_dialect.go:355: cannot use make(map[string]bool) (type map[string]bool) as type map[string]int in assignment
./mysql_dialect.go:314: cannot use make(map[string]bool) (type map[string]bool) as type map[string]int in assignment
./oracle_dialect.go:695: cannot use make(map[string]bool) (type map[string]bool) as type map[string]int in assignment
./postgres_dialect.go:939: cannot use make(map[string]bool) (type map[string]bool) as type map[string]int in assignment
./sqlite3_dialect.go:314: cannot use make(map[string]bool) (type map[string]bool) as type map[string]int in assignment

**Comment by Unknwon** [comment]
OK... maybe you would have to change `github.com/go-xorm/core` back to `edde1c5ab80e3cda107f6b93af6df894caba41ea` as wel...

**Comment by zcalusic** [comment]
Yep, that does it! Successfully started 0.9.41.0711

**Comment by Unknwon** [comment]
Thanks @zcalusic , i've notified XORM author.

**Comment by lunny** [comment]
Please upgrade to xorm latest master to resolve this issue.

**Comment by zcalusic** [comment]
I can confirm all is OK again. Tnx for a great support Unknwon & lunny!

**Comment by MojoDwarf** [comment]
I can also confirm the problem is corrected on my system as well, built and upgraded to 0.9.41.0711 without issue. Thank you very much for the support.

**Comment by doliver3** [comment]
This is still broken in 0.9.40.0711 with xorm current master

**Comment by doliver3** [comment]
2016/07/16 02:50:06 [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: do migrate: sync: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'ADD `issue_id` BIGINT(20) NULL' at line 1

It fails in the renamePullRequestFields migration.
In the xorm.log, it shows 
[xorm] [info]  2016/07/16 02:50:31.326765 [sql] ALTER TABLE  ADD `issue_id` BIGINT(20) NULL ;
There is no Table name provided in the ALTER TABLE statement which is probably why the SQL is failing.

**Comment by Unknwon** [comment]
@doliver3 `master` is not 0.9.40

**Comment by basilfx** [comment]
I know this issue is closed, but I had the same problem with the same query, while migrating from v0.6.x to latest v0.9.x.

If anyone wonders, I first migrated to v0.7.33, then to v0.9.97. No errors and no data lost (so far).
