### ISSUE TITLE
(TLS) issues on your website

### ISSUE THREAD

**Issue by rugk** [gogits/gogs#3613]
1. On gogs.io I get an OCSP Stapling error: SEC_ERROR_OCSP_INVALID_SIGNING_CERT (Firefox)
2. When I tried to mail you this I noticed your mail server does not use TLS (not even with a self-signed certificate, which can be created in seconds)
3. After registering and activating my account on https://discuss.gogs.io/ I get a "502 Bad Gateway" error.

@Unknwon Something's wrong here.

**Comment by rugk** [comment]
Okay 3. does not happen anymore.

**Comment by kmare** [comment]
Actually it's still happening to me. Firefox only, Chrome seems to be fine.

**Comment by rugk** [comment]
I cannot reproduce 3. anymore, but 1. and 2. are still valid issues.

**Comment by spawnflagger** [comment]
I also confirm this is happening on Firefox 48.0.2 (Win 10) and 48.0.1 (Mac 10.10.5).
Could be a timezone setting on the server?
(gogs.io loads without error in Chrome, Edge, Safari, Internet Explorer)

temporary workaround: in 'about:config', toggle 'security.ssl.enable_ocsp_stapling' to false.

**Comment by rugk** [comment]
That's really only a temporary workaround...
However OCSP Stapling issues are usually ignored by browsers. And yes it might be related to a wrong clock on the server.

**Comment by Unknwon** [comment]
Fixed.

**Comment by ccatlett2000** [comment]
Still happening over here. Firefox 49.0 (Latest) on [KDE Neon](https://neon.kde.org/). I've disabled OCSP checking in firefox for now, but I'd prefer to not leave a security feature in my browser disabled.

Quote from the error page:
> Invalid OCSP signing certificate in OCSP response. Error code: SEC_ERROR_OCSP_INVALID_SIGNING_CERT

**Comment by rugk** [comment]
Indeed I can confirm this. It (again/still) does not work.
