### ISSUE TITLE
Port 3000 not listening inside Docker container after upgrade

### ISSUE THREAD

**Issue by maxguru** [gogits/gogs#4358]
## Bug Description

I have upgraded my container instance, however, HTTP server in it didn't come up.  `netstat` does not show it is listening on port 3000.  However, when I bring it up fresh (no volumes), it IS listening on port 3000.

## Gogs Version
`gogs/gogs:latest`

## Git Version
`git --version` outputs `git version 2.11.1` inside the container.

## System Type
Docker container `gogs/gogs:latest`.

## Error Log
Docker container output,
```
3/28/2017 11:14:09 PMinit:socat  | Linked container DB will be binded to localhost on port 3306
3/28/2017 11:14:09 PMinit:socat  | Can't bind linked container GOGS_MYSQL_1 to localhost, port 3306 already in use
3/28/2017 11:14:09 PMinit:socat  | Can't bind linked container GOGS_GOGS_MYSQL_1 to localhost, port 3306 already in use
3/28/2017 11:14:09 PMMar 29 06:14:09 syslogd started: BusyBox v1.25.1
3/28/2017 11:14:10 PMMar 29 06:14:10 sshd[32]: Server listening on :: port 22.
3/28/2017 11:14:10 PMMar 29 06:14:10 sshd[32]: Server listening on 0.0.0.0 port 22.
3/28/2017 11:14:36 PM2017/03/29 06:14:36 [34m[TRACE] Custom path: /data/gogs[0m
3/28/2017 11:14:36 PM2017/03/29 06:14:36 [34m[TRACE] Log path: /data/app/gogs/log[0m
3/28/2017 11:14:36 PM2017/03/29 06:14:36 [34m[TRACE] Build Time: 2017-03-28 08:52:49 UTC[0m
3/28/2017 11:14:36 PM2017/03/29 06:14:36 [34m[TRACE] Build Git Hash: [0m
3/28/2017 11:14:36 PM2017/03/29 06:14:36 [34m[TRACE] Log Mode: File (Trace)[0m
3/28/2017 11:14:36 PM2017/03/29 06:14:36 [32m[ INFO] git.xxxxxxxxxxxx 0.10.32.0328 / 0.11 RC[0m
3/28/2017 11:14:59 PM2017/03/29 06:14:59 [34m[TRACE] Custom path: /data/gogs[0m
3/28/2017 11:14:59 PM2017/03/29 06:14:59 [34m[TRACE] Log path: /data/app/gogs/log[0m
3/28/2017 11:14:59 PM2017/03/29 06:14:59 [34m[TRACE] Build Time: 2017-03-28 08:52:49 UTC[0m
3/28/2017 11:14:59 PM2017/03/29 06:14:59 [34m[TRACE] Build Git Hash: [0m
3/28/2017 11:14:59 PM2017/03/29 06:14:59 [34m[TRACE] Log Mode: File (Trace)[0m
3/28/2017 11:14:59 PM2017/03/29 06:14:59 [32m[ INFO] git.xxxxxxxxxxxx 0.10.32.0328 / 0.11 RC[0m
```
Notice it doesn't say listening on 3000.  A fresh instance does.

`app/gogs/log/serv.log` doesn't have anything timestamped later than upgrade timestamp.

`app/gogs/log/xorm.log` has some stuff,
```
2017/03/29 05:57:52 [xorm] [warn]  2017/03/29 05:57:52.862555 Table repository Column name db nullable is false, struct nullable is true
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601704 Table repository has column lower_name but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601753 Table repository has column description but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601776 Table repository has column website but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601800 Table repository has column default_branch but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601822 Table repository has column num_watches but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601844 Table repository has column num_stars but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601904 Table repository has column num_forks but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601926 Table repository has column num_issues but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601947 Table repository has column num_closed_issues but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601969 Table repository has column num_pulls but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.601990 Table repository has column num_closed_pulls but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602011 Table repository has column num_milestones but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602033 Table repository has column num_closed_milestones but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602056 Table repository has column is_private but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602077 Table repository has column is_bare but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602099 Table repository has column is_mirror but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602120 Table repository has column enable_wiki but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602141 Table repository has column enable_external_wiki but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602162 Table repository has column external_wiki_url but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602193 Table repository has column enable_issues but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602221 Table repository has column enable_external_tracker but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602243 Table repository has column external_tracker_format but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602265 Table repository has column external_tracker_style but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602304 Table repository has column enable_pulls but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602326 Table repository has column is_fork but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602348 Table repository has column fork_id but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602369 Table repository has column created_unix but struct has not related field
2017/03/29 05:57:53 [xorm] [warn]  2017/03/29 05:57:53.602393 Table repository has column updated_unix but struct has not related field
```

`app/gogs/log/xorm.log` keeps getting appended with the following,
```
2017/03/29 06:18:36 [TRACE] Log Mode: File (Trace)
2017/03/29 06:18:36 [ INFO] git.xxxxxxxxxxxx 0.10.32.0328 / 0.11 RC
2017/03/29 06:18:36 [ INFO] Cache Service Enabled
2017/03/29 06:18:36 [ INFO] Session Service Enabled
2017/03/29 06:18:36 [ INFO] Mail Service Enabled
2017/03/29 06:18:36 [ INFO] Register Mail Service Enabled
2017/03/29 06:18:36 [ INFO] Notify Mail Service Enabled
2017/03/29 06:18:36 [ INFO] Migration: remove invalid protect branch whitelist
2017/03/29 06:18:36 [FATAL] [...s/routers/install.go:67 GlobalInit()] Fail to initialize ORM engine: migrate: do migrate: Error 1146: Table 'gogs.protect_branch_whitelist' doesn't exist
```

## Other information

Here is my /data/gogs/conf/app.ini,
```
APP_NAME = git.xxxxxxxxxxxx
RUN_USER = git
RUN_MODE = prod

[database]
DB_TYPE  = mysql
HOST     = db:3306
NAME     = gogs
USER     = root
PASSWD   = xxxxxxxxxxxx
SSL_MODE = disable
PATH     = data/gogs.db

[repository]
ROOT = /data/git/gogs-repositories

[server]
DOMAIN       = git.xxxxxxxxxxxx
HTTP_PORT    = 3000
ROOT_URL     = https://git.xxxxxxxxxxxx/
DISABLE_SSH  = false
SSH_PORT     = 2222
OFFLINE_MODE = true

[mailer]
ENABLED = true
HOST    = xxxxxxxxxxxx:25
FROM    = git@xxxxxxxxxxxx
USER    = git@xxxxxxxxxxxx
PASSWD  = xxxxxxxxxxxx

[service]
REGISTER_EMAIL_CONFIRM = true
ENABLE_NOTIFY_MAIL     = true
DISABLE_REGISTRATION   = true
ENABLE_CAPTCHA         = false
REQUIRE_SIGNIN_VIEW    = true

[picture]
DISABLE_GRAVATAR        = true
ENABLE_FEDERATED_AVATAR = false

[session]
PROVIDER = file

[log]
MODE      = file
LEVEL     = Info
ROOT_PATH = /data/app/gogs/log

[security]
INSTALL_LOCK = true
SECRET_KEY   = xxxxxxxxxxxx
```

I am guessing migration is failing?  How would I fix this?

**Comment by Unknwon** [comment]
Hi, this is fixed in https://github.com/gogits/gogs/pull/4361, you can now pull the latest Docker image again.

**Comment by maxguru** [comment]
I just checked `https://hub.docker.com/r/gogs/gogs/tags/`, looks like it was updated 12 mins ago.
I tried to upgrade but I still get the same problem.

**Comment by Unknwon** [comment]
Tell me your exact version of Gogs.

**Comment by maxguru** [comment]
How would I find out?  Is it in a file somewhere?

**Comment by Unknwon** [comment]
It can be found in file: templates/.VERSION

**Comment by maxguru** [comment]
```
bash-4.3# cat /app/gogs/templates/.VERSION
0.10.32.0328 / 0.11 RCbash-4.3#
```

**Comment by Unknwon** [comment]
The latest is 0.10.33.0329.

**Comment by maxguru** [comment]
Oops.. didn't pull.

Seems to be working perfectly now.
