### ISSUE TITLE
An error has occurred : initRepository: createDelegateHooks: create delegate hook ... /hooks/pre-receive ... no such file or directory

### ISSUE THREAD

**Issue by lidouf** [gogits/gogs#4598]
- Gogs version (or commit ref): 0.11.19 armv5
- Git version: 2.12.2
- Operating system: armv7l GNU/Linux synology_monaco_ds216play
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL(mariadb actually)
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist (usually found in `log/gogs.log`):

> 
> 2017/07/02 13:12:59 [TRACE] Session ID: bae97ecadb21beb3
> 2017/07/02 13:12:59 [TRACE] CSRF Token: HsrVTb3UlWFifWTwIRiSwqtIaUQ6MTQ5ODk3MjIzMDQxNDgzNjMyNw==
> 2017/07/02 13:12:59 [TRACE] Template: repo/create
> 2017/07/02 13:13:23 [TRACE] Session ID: bae97ecadb21beb3
> 2017/07/02 13:13:23 [TRACE] CSRF Token: HsrVTb3UlWFifWTwIRiSwqtIaUQ6MTQ5ODk3MjIzMDQxNDgzNjMyNw==
> 2017/07/02 13:13:23 [ERROR] [...routers/repo/repo.go:102 handleCreateError()] CreatePost: initRepository: createDelegateHooks: create delegate hook '/volume1/gogs_repos/lidou/home_test.git/hooks/pre-receive': open /volume1/gogs_repos/lidou/home_test.git/hooks/pre-receive: no such file or directory
> 2017/07/02 13:13:23 [TRACE] Template: status/500

## Description

After I upgraded gogs to v0.11.19.0609(armv5), I create a new repo, It says:

![2017-07-02 14-00-17](https://user-images.githubusercontent.com/9838763/27767604-2dc17380-5f2f-11e7-967a-0dec87a4969f.png)

> 
> An error has occurred : initRepository: createDelegateHooks: create delegate hook '/volume1/gogs_repos/lidou/home_test.git/hooks/pre-receive': open /volume1/gogs_repos/lidou/home_test.git/hooks/pre-receive: no such file or directory
> 
> Application Version: 0.11.19.0609

The older version worked fine for me, It's v0.9.141(armv6).

**Comment by seokbeomKim** [comment]
Same here. I was looking for working version on armv7l.
None of version(>=0.11) works well. I should test the older version 0.9.141.

**Comment by seokbeomKim** [comment]
As you said, it is possible to create repository without any problems on 0.9.141.

**Comment by tseel** [comment]
In my case the issues results of missing templates of the git installation. Usually they should reside in /usr/share/git-core/templates/ or /opt/share/git-core/templates/ depending on the git setup. If they are missing, git doesn't copy them over to the initialized repo and createDelegateHooks will fail.
As the copied hooks are just samples, gogs could just create the folders needed and then create it's own hooks.

So, the temporary workaround for the problem is to provide git with the templates from e.g. another git setup. After that, the creation finished without errors. 
It can also be checked on commandline if initializing a bare repo creates the hooks folder as well.

**Comment by seokbeomKim** [comment]
Thanks for reply. The problem has been solved!

**Comment by lidouf** [comment]
Thanks tseel. U gave me big help.

**Comment by tangm421** [comment]
I was manual setup git 2.13.2 before. the templates of git located in `/usr/local/share/git-core/`. But it is still failed when I copy git templates folder to `/usr/share/git-core/`. So I just rollback gogs to version 0.9.141.0211 and it`s work fine.
