### ISSUE TITLE
High CPU usage of lastest version (0.5.10.1229 Beta)

### ISSUE THREAD

**Issue by TonyTsangHK** [gogits/gogs#820]
After updating gogs to 0.5.10 (build from source)
gogs web eat up 99.99% of CPU cycle and never drop.

When falling back to version 0.5.9.1213 Beta (Binary build) or 0.5.8.1125 Beta (build from source), CPU usage back to normal around (~2% when idle).

**Comment by Unknwon** [comment]
This is happening to demo server, too. I've found it's because it's executing `git-fsck`, and I'm adding a switch option for this.

**Comment by TonyTsangHK** [comment]
Yes, after monitoring the server for a few hours.
git fsck seems to be the cause of high CPU usage.

This is my server's CPU usage graph.
![cpu-day](https://cloud.githubusercontent.com/assets/9127722/5594790/0f33db0e-9297-11e4-85f0-9f89c618765b.png)

There are a constant CPU spikes per hours. 
Around 10:00 the CPU usage stay at 100% and never drop until I stop gogs web and down grade to v0.5.9.

But I cannot reproduce this by switching back v0.5.10, maybe there is some misconfiguration on my side.

I think there should also be a configuration option to control the frequency of git fsck.

I don't known much about git fsck, is it necessary to run per hour?

**Comment by Unknwon** [comment]
Hi, I've pushed a fix on `dev` which make 24 hours as default interval, and of course, you're now able to disable it.

**Comment by TonyTsangHK** [comment]
Still no luck with 0.5.11.0102 Beta.
I've tried to reset all my custom settings but got the same result (top command showing gogs eat up 99% of CPU cycle).

This how I build gogs from, am I doing it wrong?
cd $GOPATH/src/github.com/gogits/gogs
git pull
git checkout dev
go get -u -tags "redis" ./...
go build -tags "redis"
cp -r /opt/gogs/custom/ ./custom

Thanks for the hard work, but I better stay at v0.5.9 right now until I found what was wrong with my server.

**Comment by Unknwon** [comment]
Looks like git-fsck just one reason, and there is something deadlock.

**Comment by Unknwon** [comment]
@TonyTsangHK OK, I've found this is a bug in macaron-contrib/cache , fixes are pushed.

**Comment by TonyTsangHK** [comment]
It works!

Good job
